import React from 'react'
import Navbar from './Navbar'
import Footer from './Footer'
import { Outlet } from 'react-router-dom'

export default function Layout() {
  return (
    <div>
          <Navbar />
          <Outlet />
          <Footer />
    </div>
  )
}


// {
//         id: 10,
//         title: "Modern Upholstered Accent Chair",
//         slug: "modern-upholstered-accent-chair",
//         img: "/TopProImg/Image (19).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#BFA6A0",
//         colVisible2: "#EAD7C4",
//         colVisible3: "#FAF3F0",
//         category: "Sitting Room",
//         price: "$24",
//         newPrice: "$22",
//         discount: "9%",
//         important: true,
//         rate: 3,
//     },
//     {
//         id: 11,
//         title: "Utopia Plant Pots",
//         slug: "utopia-plant-pots",
//         img: "/TopProImg/Image (11).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#8A6D6B",
//         colVisible2: "#D2B1A3",
//         colVisible3: "#F1ECE9",
//         category: "Accessories",
//         price: "$8",
//         newPrice: "$7.5",
//         discount: "2%",
//         important: false,
//         rate: 4,
//     },
//     {
//         id: 12,
//         title: "Roundhill Fabric Accent Chair",
//         slug: "roundhill-fabric-accent-chair",
//         img: "/TopProImg/Image (12).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#C9B1A9",
//         colVisible2: "#E9DAD0",
//         colVisible3: "#FFF8F3",
//         category: "Accessories",
//         price: "$8",
//         newPrice: "$5",
//         discount: "35%",
//         important: false,
//         rate: 2,
//     },
//     {
//         id: 13,
//         title: "Round Terra Marble Center Table",
//         slug: "round-terra-marble-center-table",
//         img: "/TopProImg/Image (13).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#91785D",
//         colVisible2: "#D9C5B2",
//         colVisible3: "#F5F2EE",
//         category: "Kitchen",
//         price: "$34",
//         newPrice: "$30",
//         discount: "20%",
//         important: false,
//         rate: 4,
//     },
//     {
//         id: 14,
//         title: "Ceramic Rustic Vase Matte",
//         slug: "ceramic-rustic-vase-matte",
//         img: "/TopProImg/Image (14).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#A99587",
//         colVisible2: "#E1CFC2",
//         colVisible3: "#FBF6F2",
//         category: "Accessories",
//         price: "$11",
//         newPrice: "$10",
//         discount: "10%",
//         important: false,
//         rate: 3,
//     },
//     {
//         id: 15,
//         title: "Metro Luxe Duo Sofa",
//         slug: "metro-luxe-duo-sofa",
//         img: "/TopProImg/Image (15).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#9B7E6E",
//         colVisible2: "#D7C2B3",
//         colVisible3: "#F8F4F0",
//         category: "Sitting Room",
//         price: "$120",
//         newPrice: "$110",
//         discount: "20%",
//         important: false,
//         rate: 5,
//     },
//     {
//         id: 16,
//         title: "Kitchen Bar Stool",
//         slug: "kitchen-bar-stool",
//         img: "/TopProImg/Image (16).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#836953",
//         colVisible2: "#CDB7A3",
//         colVisible3: "#F1ECE7",
//         category: "Sitting Room",
//         price: "$19",
//         newPrice: "$18",
//         discount: "2%",
//         important: false,
//         rate: 4,
//     },
//     {
//         id: 17,
//         title: "Luxe Modern Armchair",
//         slug: "luxe-modern-armchair",
//         img: "/TopProImg/Image (17).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#8E7C6B",
//         colVisible2: "#D2C1AF",
//         colVisible3: "#F6F2ED",
//         category: "Sitting Room",
//         price: "$60",
//         newPrice: "$49",
//         discount: "40%",
//         important: false,
//         rate: 5,
//     },
//     {
//         id: 18,
//         title: "Round Fluted Accent Center Table",
//         slug: "round-fluted-accent-center-table",
//         img: "/TopProImg/Image (18).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#927D6C",
//         colVisible2: "#D6C6B5",
//         colVisible3: "#F7F4F1",
//         category: "Kitchen",
//         price: "$129",
//         newPrice: "$110",
//         discount: "20%",
//         important: false,
//         rate: 4,
//     },
//     {
//         id: 19,
//         title: "Round Terra Marble Side Table",
//         slug: "round-terra-marble-side-table",
//         img: "/TopProImg/Image (19).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#9A8475",
//         colVisible2: "#DCCFC3",
//         colVisible3: "#FAF7F4",
//         category: "Kitchen",
//         price: "$11",
//         newPrice: "$7",
//         discount: "60%",
//         important: false,
//         rate: 3,
//     },
//     {
//         id: 20,
//         title: "Boucle Accent Chair",
//         slug: "boucle-accent-chair-2",
//         img: "/TopProImg/Image (20).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#AD8D7F",
//         colVisible2: "#E2D1C5",
//         colVisible3: "#FCF9F6",
//         category: "Sitting Room",
//         price: "$14",
//         important: false,
//         rate: 2,
//     },
//     {
//         id: 21,
//         title: "Boucle Accent Chair",
//         slug: "boucle-accent-chair-3",
//         img: "/TopProImg/Image (1).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#A0816F",
//         colVisible2: "#D9C7B8",
//         colVisible3: "#F7F5F2",
//         category: "Sitting Room",
//         price: "$14",
//         important: false,
//         rate: 3,
//     }

// export const TopProductsData = [
//     {
//         id: 1,
//         title: "Faux Leather Sofa Couch",
//         slug: "faux-leather-sofa-couch",
//         img: "/TopProImg/Image (1).png",
//         color1: "#d58544",
//         color2: "rgb(216, 190, 175)",
//         colVisible1: "#8B5E3C",
//         colVisible2: "#C6AA92",
//         colVisible3: "#EEE2DC",
//         category: "Sitting Room",
//         price: "$129",
//         newPrice: "$112",
//         discount: "15%",
//         important: true,
//         rate: 4,
//         description: "Elegant faux leather sofa perfect for modern sitting rooms, offering both style and comfort.",
//     },
//     {
//         id: 2,
//         title: "Minimalist Chair",
//         slug: "minimalist-chair",
//         img: "/TopProImg/Image (2).png",
//         color1: "#6d5846",
//         color2: "#c8b6a6",
//         colVisible1: "#5E4B3C",
//         colVisible2: "#BFA897",
//         colVisible3: "#E8DED7",
//         category: "Sitting Room",
//         price: "$85",
//         important: false,
//         rate: 5,
//         description: "Sleek and minimalist chair that fits any modern or classic decor with ease.",
//     },
//     {
//         id: 3,
//         title: "Beige Modern Chair",
//         slug: "beige-modern-chair",
//         img: "/TopProImg/Image (3).png",
//         color1: "#d5c4b4",
//         color2: "#f4f1ee",
//         colVisible1: "#CBB9A8",
//         colVisible2: "#F2EDE8",
//         colVisible3: "#FFFDFB",
//         category: "Sitting Room",
//         price: "$110",
//         newPrice: "$99",
//         discount: "10%",
//         important: true,
//         rate: 3,
//         description: "Comfortable beige chair with a modern design, perfect for cozy corners.",
//     },
//     {
//         id: 4,
//         title: "Modern Light Lamp",
//         slug: "modern-light-lamp",
//         img: "/TopProImg/Image (4).png",
//         color1: "#e9dbc8",
//         color2: "#fdfaf6",
//         colVisible1: "#DAC8B4",
//         colVisible2: "#F5EFE9",
//         colVisible3: "#FFFCFA",
//         category: "Lighting",
//         price: "$45",
//         important: false,
//         rate: 4,
//         description: "Soft ambient lighting with a sleek look to match modern interiors.",
//     },
//     {
//         id: 5,
//         title: "Fabric Sofa Couch",
//         slug: "fabric-sofa-couch",
//         img: "/TopProImg/Image (5).png",
//         color1: "#b6a59f",
//         color2: "#d8ccc6",
//         colVisible1: "#9E8E88",
//         colVisible2: "#CFC3BD",
//         colVisible3: "#F2ECEA",
//         category: "Sitting Room",
//         price: "$175",
//         important: true,
//         rate: 5,
//         description: "Classic fabric sofa with neutral tones, adds elegance and comfort to any space.",
//     },
//     {
//         id: 6,
//         title: "Wood Table",
//         slug: "wood-table",
//         img: "/TopProImg/Image (6).png",
//         color1: "#a18267",
//         color2: "#c4a98a",
//         colVisible1: "#917256",
//         colVisible2: "#B89E82",
//         colVisible3: "#EFE8E0",
//         category: "Tables",
//         price: "$140",
//         important: false,
//         rate: 3,
//         description: "Solid wood table with natural finish, ideal for dining or decor setups.",
//     },
//     {
//         id: 7,
//         title: "Double Sofa",
//         slug: "double-sofa",
//         img: "/TopProImg/Image (7).png",
//         color1: "#8a7d72",
//         color2: "#bfb4a9",
//         colVisible1: "#796C62",
//         colVisible2: "#B0A59B",
//         colVisible3: "#EAE3DD",
//         category: "Sitting Room",
//         price: "$210",
//         important: true,
//         rate: 4,
//         description: "Spacious double sofa for comfortable seating, crafted with soft fabric and neutral tones.",
//     },
//     {
//         id: 8,
//         title: "Decorative Lamp",
//         slug: "decorative-lamp",
//         img: "/TopProImg/Image (8).png",
//         color1: "#e2d9cd",
//         color2: "#f4f0eb",
//         colVisible1: "#CFC6BB",
//         colVisible2: "#EBE6E1",
//         colVisible3: "#FDFBF9",
//         category: "Lighting",
//         price: "$39",
//         important: false,
//         rate: 4,
//         description: "Elegant table lamp to elevate your room with soft, warm glow.",
//     },
//     {
//         id: 9,
//         title: "Round Center Table",
//         slug: "round-center-table",
//         img: "/TopProImg/Image (9).png",
//         color1: "#ad9d93",
//         color2: "#d4c7be",
//         colVisible1: "#99897F",
//         colVisible2: "#C7BBB2",
//         colVisible3: "#F3EEEA",
//         category: "Tables",
//         price: "$99",
//         important: true,
//         rate: 5,
//         description: "Modern round table with a minimalist design, perfect for living rooms.",
//     },
//     {
//         id: 10,
//         title: "Wooden Coffee Table",
//         slug: "wooden-coffee-table",
//         img: "/TopProImg/Image (10).png",
//         color1: "#A47551",
//         color2: "#E6D3B3",
//         colVisible1: "#8B5E3C",
//         colVisible2: "#CBB89D",
//         colVisible3: "#F5ECD9",
//         category: "Living Room",
//         price: "$99",
//         newPrice: "$79",
//         discount: "20%",
//         important: false,
//         rate: 4,
//         description: "A rustic wooden coffee table perfect for cozy living rooms.",
//     },
//     {
//         id: 11,
//         title: "Modern TV Stand",
//         slug: "modern-tv-stand",
//         img: "/TopProImg/Image (11).png",
//         color1: "#3A3A3A",
//         color2: "#DADADA",
//         colVisible1: "#2C2C2C",
//         colVisible2: "#B0B0B0",
//         colVisible3: "#F0F0F0",
//         category: "Entertainment",
//         price: "$159",
//         newPrice: "$135",
//         discount: "15%",
//         important: false,
//         rate: 5,
//         description: "Sleek modern TV stand with plenty of storage and style.",
//     },
//     {
//         id: 12,
//         title: "Fabric Armchair",
//         slug: "fabric-armchair",
//         img: "/TopProImg/Image (12).png",
//         color1: "#6C757D",
//         color2: "#CED4DA",
//         colVisible1: "#5A6268",
//         colVisible2: "#ADB5BD",
//         colVisible3: "#E9ECEF",
//         category: "Sitting Room",
//         price: "$89",
//         newPrice: "$75",
//         discount: "16%",
//         important: false,
//         rate: 4,
//         description: "Comfortable fabric armchair ideal for reading corners or small spaces.",
//     },
//     {
//         id: 13,
//         title: "Glass Dining Table",
//         slug: "glass-dining-table",
//         img: "/TopProImg/Image (13).png",
//         color1: "#E0E0E0",
//         color2: "#A0A0A0",
//         colVisible1: "#D0D0D0",
//         colVisible2: "#B8B8B8",
//         colVisible3: "#F8F8F8",
//         category: "Dining Room",
//         price: "$249",
//         newPrice: "$199",
//         discount: "20%",
//         important: true,
//         rate: 5,
//         description: "Elegant glass-top dining table with a minimalist metal frame.",
//     },
//     {
//         id: 14,
//         title: "Wall-Mounted Bookshelf",
//         slug: "wall-mounted-bookshelf",
//         img: "/TopProImg/Image (14).png",
//         color1: "#8D6748",
//         color2: "#F0EAD6",
//         colVisible1: "#7C543A",
//         colVisible2: "#C6B89F",
//         colVisible3: "#EFE7D0",
//         category: "Study Room",
//         price: "$59",
//         newPrice: "$49",
//         discount: "17%",
//         important: false,
//         rate: 4,
//         description: "Stylish wall-mounted bookshelf to maximize your storage space.",
//     },
//     {
//         id: 15,
//         title: "Classic Bed Frame",
//         slug: "classic-bed-frame",
//         img: "/TopProImg/Image (15).png",
//         color1: "#B5651D",
//         color2: "#FFF3E2",
//         colVisible1: "#9E4E0E",
//         colVisible2: "#EAC9A6",
//         colVisible3: "#FDEBD3",
//         category: "Bedroom",
//         price: "$349",
//         newPrice: "$299",
//         discount: "14%",
//         important: true,
//         rate: 5,
//         description: "Solid wood bed frame with classic design for a timeless bedroom.",
//     },
//     {
//         id: 16,
//         title: "Recliner Chair",
//         slug: "recliner-chair",
//         img: "/TopProImg/Image (16).png",
//         color1: "#4B3621",
//         color2: "#A1887F",
//         colVisible1: "#3E2C1A",
//         colVisible2: "#8E7A6C",
//         colVisible3: "#D7CCC8",
//         category: "Living Room",
//         price: "$199",
//         newPrice: "$169",
//         discount: "15%",
//         important: false,
//         rate: 4,
//         description: "Relax in luxury with this soft and adjustable recliner chair.",
//     },
//     {
//         id: 17,
//         title: "Minimalist Desk",
//         slug: "minimalist-desk",
//         img: "/TopProImg/Image (17).png",
//         color1: "#CCCCCC",
//         color2: "#F4F4F4",
//         colVisible1: "#B0B0B0",
//         colVisible2: "#DADADA",
//         colVisible3: "#FFFFFF",
//         category: "Home Office",
//         price: "$129",
//         newPrice: "$109",
//         discount: "16%",
//         important: false,
//         rate: 5,
//         description: "Clean and functional minimalist desk for your productive space.",
//     },
//     {
//         id: 18,
//         title: "Nightstand with Drawer",
//         slug: "nightstand-with-drawer",
//         img: "/TopProImg/Image (18).png",
//         color1: "#5C3A21",
//         color2: "#D7CCC8",
//         colVisible1: "#4B2E18",
//         colVisible2: "#BFAFA4",
//         colVisible3: "#EFE6E1",
//         category: "Bedroom",
//         price: "$79",
//         newPrice: "$65",
//         discount: "17%",
//         important: false,
//         rate: 4,
//         description: "Handy nightstand with drawer, combining function with style.",
//     },
//     {
//         id: 19,
//         title: "Upholstered Bench",
//         slug: "upholstered-bench",
//         img: "/TopProImg/Image (19).png",
//         color1: "#9E9E9E",
//         color2: "#E0E0E0",
//         colVisible1: "#8C8C8C",
//         colVisible2: "#CFCFCF",
//         colVisible3: "#F5F5F5",
//         category: "Hallway",
//         price: "$119",
//         newPrice: "$99",
//         discount: "17%",
//         important: false,
//         rate: 3,
//         description: "Versatile upholstered bench suitable for entryways or bedroom foot.",
//     },
//     {
//         id: 20,
//         title: "Kid’s Bunk Bed",
//         slug: "kids-bunk-bed",
//         img: "/TopProImg/Image (20).png",
//         color1: "#F4A261",
//         color2: "#FFE5B4",
//         colVisible1: "#E07B39",
//         colVisible2: "#FFCEA0",
//         colVisible3: "#FFF6E6",
//         category: "Kids Room",
//         price: "$399",
//         newPrice: "$349",
//         discount: "13%",
//         important: true,
//         rate: 5,
//         description: "Fun and safe bunk bed for kids, with solid build and vibrant colors.",
//     },
//     {
//         id: 21,
//         title: "Foldable Dining Chairs (Set of 2)",
//         slug: "foldable-dining-chairs",
//         img: "/TopProImg/Image (21).png",
//         color1: "#6D4C41",
//         color2: "#D7CCC8",
//         colVisible1: "#5C3B32",
//         colVisible2: "#BFAFA4",
//         colVisible3: "#EFE6E1",
//         category: "Dining Room",
//         price: "$89",
//         newPrice: "$75",
//         discount: "16%",
//         important: false,
//         rate: 4,
//         description: "Space-saving foldable dining chairs, great for compact dining areas.",
//     },
// ];